builds:
- env:
  - CGO_ENABLED=0
  binary: manager
  goos:
  - linux
  goarch:
  - amd64
changelog:
  filters:
    exclude:
    - '^docs'
    - '^test'
    - '^feat'
    - '^chore'
    - '^Merge '
    - '[Ty]ypo'
release:
  draft: true
