on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        # required for the changelog to work correctly
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      -
        name: prepare changelog
        run: |
          tag=${{ github.ref }}
          tag=${tag##*/}
          cat <<EOF | tee /tmp/release.txt
          ## Docker images

          - \`docker pull goharbor/harbor-cluster-operator:$tag\`
          EOF
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.144.1
          args: release --rm-dist --release-footer /tmp/release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # opspresso/action-docker use body of ./target/TAG_NAME as docker tag
    # https://github.com/opspresso/action-docker#common-env
    - run: mkdir ./target
    - run: echo -n '${{ github.ref }}' | sed 's|refs/tags/||' > ./target/TAG_NAME
    - name: Docker Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: '${{ secrets.DOCKER_USER }}'
        PASSWORD: '${{ secrets.DOCKER_TOKEN }}'
        LATEST: 'false'
